version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: warehousedb
    environment:
      POSTGRES_USER: warehouseuser
      POSTGRES_PASSWORD: warehousepass
      POSTGRES_DB: warehousedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U again -d again"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: